site_name: 校级智能计算平台用户手册
site_url: 'https://cc.ruc.edu.cn/help/'

theme:
  name: 'material'
  language: 'zh'
  favicon: 'images/favicon.png'

copyright: Copyright © 中国人民大学大型科学仪器共享平台

markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: True

plugins:
    - redirects:
        redirect_maps:
            'app/Jupyterlab-With-GPU.md': 'app/Jupyterlab.md'
        
extra_css:
  - stylesheets/extra.css
          
nav:
    - '首页': 'index.md'
    - '使用必读':
      - '用户注册': 'manual/login.md'
      - '使用模式': 'manual/usage-mode.md'
      - '数据管理与文件传输': 'manual/transfer.md'
      - 'SSH客户端': 'manual/ssh.md'

    - '软件使用':
      - '共享集群': 
        - 'Slurm共享集群': 'app/GPU-Cluster.md'
        - 'Slurm进阶': 'app/slurm-advanced.md'
        - 'module/spack': 'app/module-spack.md'
      - 'conda': 'app/conda.md'
      - 'Python和深度学习':
        - 'Jupyter': 'app/Jupyterlab.md'
        - '在共享集群上提交作业': 'app/public-cluster-python.md'
      - 'MATLAB': 
        - '交互式MATLAB': 'app/matlab.md'
        - '在共享集群上提交作业': 'app/public-cluster-matlab.md'
      - 'R' :
        - 'RStudio': 'app/RStudio.md'
        - '在共享集群上提交作业' : 'app/public-cluster-r.md'
      - 'Stata': 'app/stata.md'
      - '分子动力学':
        - 'Amber': 'app/amber.md'
    
    - '系列培训及相关资料': 'tutorials.md'
