site_name: 校级计算平台用户手册
site_url: "https://cc.ruc.edu.cn/help/"
repo_url: "https://github.com/ruc-cc/cc-help-docs"
repo_name: ruc-cc/cc-help-docs
theme:
  icon:
    repo: fontawesome/brands/git-alt

theme:
  name: "material"
  language: "zh"
  favicon: "images/favicon.png"
  font: false

copyright: Copyright © 中国人民大学大型科学仪器共享平台

use_directory_urls: false

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: True

plugins:
  - mkdocs-video
  - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]+'

extra_css:
  - stylesheets/extra.css

nav:
  - "首页": "index.md"
  - "使用必读":
      - "用户注册": "manual/login.md"
      - "使用模式": "manual/usage-mode.md"
      - "课题组团队管理": "manual/project.md"
      - "计费统计": "manual/bill.md"
      - "数据管理与文件传输": "manual/transfer.md"
      - "SSH客户端": "manual/ssh.md"
      - "校外访问与VPN": "manual/vpn.md"
  - "共享集群":
      - "SLURM共享集群": "slurm/GPU-Cluster.md"
      - "课题组共享文件夹": "slurm/slurm-share.md"
      - "SLURM进阶": "slurm/slurm-advanced.md"
      - "网络": "slurm/network.md"
      - "存储": "slurm/storage.md"
      - "module/spack": "slurm/module-spack.md"
      - "编译器": "slurm/compilers.md"
      - "MPI": "slurm/mpi.md"
      - "Python": "slurm/public-cluster-python.md"
      - "R": "slurm/public-cluster-r.md"
      - "MATLAB": "slurm/public-cluster-matlab.md"
      - "Amber": "slurm/amber.md"
      - "容器：Docker与Singularity": "slurm/docker-singularity.md"
  
  - "交互实例":
      - "VSCode": "instance/vscode.md"
      - "JupyterLab": "instance/jupyterlab.md"
      - "RStudio": "instance/rstudio.md"
      - "MATLAB": "instance/matlab.md"
      - "Stata": "instance/stata.md"

  - "虚拟机":
      - "Windows虚拟机": "virtual/windows.md"
      - "Linux虚拟机": "virtual/linux-virtual.md"
  
  - "通用软件":      
      - "conda/mamba": "app/conda.md" 
      - "CUDA": "app/cuda.md"
  - "常见问题FAQ": "faq.md"
  - "收费奖励标准": "fee.md"
  - "培训及相关资料": "tutorials.md"
  - "管理办法": "regulation.md"