site_name: 校级计算平台用户手册
site_url: "https://cc.ruc.edu.cn/help/"
repo_url: "https://github.com/ruc-cc/cc-help-docs"
repo_name: ruc-cc/cc-help-docs
theme:
  icon:
    repo: fontawesome/brands/git-alt

theme:
  name: "material"
  language: "zh"
  favicon: "images/favicon.png"
  font: false

copyright: Copyright © 中国人民大学大型科学仪器共享平台

use_directory_urls: false

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: True

plugins:
  - mkdocs-video
  - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]+'

extra_css:
  - stylesheets/extra.css

nav:
  - "首页": "index.md"
  - "使用必读":
      - "用户注册": "manual/login.md"
      - "使用模式": "manual/usage-mode.md"
      - "课题组团队管理": "manual/project.md"
      - "计费统计": "manual/bill.md"
      - "数据管理与文件传输": "manual/transfer.md"
      - "SSH客户端": "manual/ssh.md"
      - "校外访问与VPN": "manual/vpn.md"

  - "软件使用":
      - "共享集群":
          - "SLURM共享集群": "app/GPU-Cluster.md"
          - "课题组共享文件夹": "app/slurm-share.md"
          - "SLURM进阶": "app/slurm-advanced.md"
          - "网络": "app/network.md"
          - "存储": "app/storage.md"
          - "module/spack": "app/module-spack.md"
          - "编译器": "app/compilers.md"
          - "MPI": "app/mpi.md"
          - "Python": "app/public-cluster-python.md"
          - "R": "app/public-cluster-r.md"
      - "VSCode": "app/vscode.md"
      - "JupyterLab": "app/jupyterlab.md"
      - "RStudio": "app/rstudio.md"
      - "MATLAB":
          - "交互式MATLAB": "app/matlab.md"
          - "在共享集群上提交作业": "app/public-cluster-matlab.md"
      - "Stata": "app/stata.md"
      - "Windows虚拟机": "app/windows.md"
      - "Linux虚拟机": "app/linux-virtual.md"
      - "分子动力学":
          - "Amber": "app/amber.md"
      - "conda/mamba": "app/conda.md"
      - "容器：Docker与Singularity": "app/docker-singularity.md"
      - "CUDA": "app/cuda.md"

  - "常见问题FAQ": "faq.md"
  - "收费奖励标准": "fee.md"
  - "培训及相关资料": "tutorials.md"
  - "管理办法": "regulation.md"
